# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"8\n\x0bStudentInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ra\x18\x02 \x01(\t\x12\x0f\n\x07\x63redits\x18\x03 \x01(\x05\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\x07Greeter\x12H\n\x18StudentHasVacancyReserve\x12\x17.helloworld.StudentInfo\x1a\x11.helloworld.Reply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_STUDENTINFO']._serialized_start=32
  _globals['_STUDENTINFO']._serialized_end=88
  _globals['_REPLY']._serialized_start=90
  _globals['_REPLY']._serialized_end=114
  _globals['_GREETER']._serialized_start=116
  _globals['_GREETER']._serialized_end=199
# @@protoc_insertion_point(module_scope)
